### ISSUE TITLE
Request for Feature Branch

### ISSUE THREAD

**Issue by remmahad** [digiaiiris/zabbix-azure-monitoring#23]
Hey there,

you and your code helped me a lot with my monitoring project.
I tried to monitor azure application insights with zabbix and your python code did a great job!

I did some improvements in the README and documentation section. 
You can see them in my own repo (fork of yours).

Maybe you are interested to compare our code?
I tried to create a feature branch, but i think it's not possible for me right now.

I look forward to hearing from you!<

Update: And mayybe you can explain your UserParamaterConf for me, because I'm a little bit confused about this code:
```
source /opt/virtualenv/zabbix-azure-monitoring/bin/activate
```

**Comment by bulkware** [comment]
Hello!

Thank you for your input. Could you please create a pull request to our original repository using your fork? That way we could review the changes, suggest additional changes and finally merge those changes?

The "source" part is an activation for a virtual environment to run the script. It includes Python, libraries and the scripts in an isolated environment so if we need to do any changes or update something, we won't break any other scripts that might be on the target server. Read more here: https://docs.python.org/3/tutorial/venv.html
